# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Volunteer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Volunteer
  pod 'Parse'
  pod 'AlamofireImage'
  pod 'SideMenu'
  pod 'Firebase/Analytics'
  pod 'Firebase/Functions'

  target 'VolunteerTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Parse'
    pod 'AlamofireImage'
    pod 'SideMenu'
    pod 'Firebase/Analytics'
    pod 'Firebase/Functions'
  end

  target 'VolunteerUITests' do
    # Pods for testing
    pod 'Parse'
    pod 'AlamofireImage'
    pod 'SideMenu'
    pod 'Firebase/Analytics'
    pod 'Firebase/Functions'
  end

end
